services:
  - type: web
    name: chocolate-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=8000 --server.enableCORS=false
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
